### ISSUE TITLE
[Request] :  Enhanced tests for each connection

### ISSUE THREAD

**Issue by RexBytes** [RexBytes/pgmonkey#1]
Each connection type, (normal, normal pool, async, async pool), has a basic connection test.

Can this be expanded for each test.

For example, for the pool connections actually test the generation of a pool of connections.
Output would include,

- Pool created,
- Pool connection 1 tested
- Pool connection 2 tested

etc...

**Comment by aleroldan156** [comment]
try this

https://bit.ly/4eugCty

you may need to install the c compiler

**Comment by RexBytes** [comment]
Added in V1.0.3

**Comment by RexBytes** [comment]
Added in V1.0.3
